### ISSUE TITLE
Cannot change name of opsgenie_api_integration after creation

### ISSUE THREAD

**Issue by teddylear** [opsgenie/terraform-provider-opsgenie#50] opened 2019-12-12 22:53 UTC
### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
opsgenie_api_integration

### Terraform Configuration Files
```hcl
data "opsgenie_team" "opsgenie" {
  name = "test_team"
}

resource "opsgenie_api_integration" "cloudwatch" {
  name  = "test_A"
  type   = "CloudWatch"
  owner_team_id = "${data.opsgenie_team.opsgenie.id}"
}
```

### Expected Behavior
Should be able to change name of opsgenie_api_integration resource "cloudwatch" from "test_A" to "test_B" 

### Actual Behavior
Got an error with 403 response code: "You can not assign integration to another team" after changing opsgenie_api_integration resource "cloudwatch" to "test_B"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change name of opsgenie_api_integration to "team_B"
3. `terrform apply`

**Comment by ffahri** [comment] 2020-02-02 14:55
Hey @KenJamesLear i could not reproduce this issue can you please share more info of the issue

1. I created integration with owner team
2. Changed name of the integration and applied
3. Success 

Creating integration
```
resource "opsgenie_api_integration" "example-api-integration" {
  name = "api-based-int"
  type = "API"
  owner_team_id = "${opsgenie_team.test.id}"
}
```

Changing the name
```
resource "opsgenie_api_integration" "example-api-integration" {
  name = "api-based-int2"
  type = "API"
  owner_team_id = "${opsgenie_team.test.id}"
}
```

```
      ~ name                   = "api-based-int-again" -> "api-based-int-again2"
...
..

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by milonjames** [comment] 2020-03-26 12:27
@ffahri I am experiencing the same issue. I am using an API key from an API integration which I have created under my 'team' to authenticate Terraform to OpsGenie. I don't have access to create a global API key in my Opsgenie account. Could that be an issue? 

Creation completes successfully, however if I try to change any of the arguments it will result in the following error.

Error: Error occurred with Status code: 403, Message: You can not assign integration to another team

**Comment by milonjames** [comment] 2020-03-27 04:44
@ffahri I think this could be due to a bug in opsgenie-go-sdk-v2. See the function 'ForceUpdateAllFields'

https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/v1.1/integration/integration.go#L57

There we can see that it's not passing the 'OwnerTeam' argument to the request. And in my trial runs using curl, I found that if I try to update an integration without passing the 'ownerTeam' argument in the JSON payload, it will result in the same error.

`curl -X PUT 'https://api.eu.opsgenie.com/v2/integrations/<integration_id>' --header 'Authorization: GenieKey<API_KEY>' --header 'Content-Type: application/json' --data 
'{
     "enabled": true,
       "ignoreRespondersFromPayload": true,
       "name": "<INTEGRATION_NAME>",
       "suppressNotifications": true,
       "responders": [],
       "type": "API"
}'`

{"code":40301,"message":"You can not assign integration to another team","took":0.002,"requestId":"2986a890-3fd3-4f5e-973b-4e6034c5936a"}

**Comment by ffahri** [comment] 2020-04-06 12:00
Hey @milonjames global level integrations and policies requires different plan.
We are waiting upstream response for owner team transition

**Comment by ffahri** [comment] 2020-04-06 12:01
Im closing this issue we can continue from #77

**Closed as completed by ffahri** 2020-04-06 12:01 UTC
